export const PageRoutes = {
    GETTING_STARTED_DOTNET_API: '/getting-started-dotnet-api',
    ENTITY_FRAMEWORK_CORE_SETUP: '/entity-framework-core-setup',
    CREATING_API_CONTROLLERS: '/creating-api-controllers',
    MANIPULATING_RESOURCES_VALIDATING_INPUT: '/manipulating-resources-validating-input',
    VALIDATING_INPUT_DATA_ANNOTATIONS: '/validating-input-data-annotations',
    WORKING_WITH_SERVICES_DEPENDENCY_INJECTION: '/working-with-services-dependency-injection',
    HANDLING_ASYNCHRONOUS_REQUESTS: '/handling-asynchronous-requests',
    SEARCHING_FILTERING_PAGING_RESOURCES: '/searching-filtering-paging-resources',
    SECURING_API_AUTHENTICATION_AUTHORIZATION: '/securing-api-authentication-authorization',
    ADVANCED_API_SECURITY_OAUTH_JWT_HTTPS: '/advanced-api-security-oauth-jwt-https',
    HANDLING_CORS_REQUESTS: '/handling-cors-requests',
    LOGGING_EXCEPTION_HANDLING_MIDDLEWARE: '/logging-exception-handling-middleware',
    ERROR_RESPONSE_STATUS_CODES: '/error-response-status-codes',
    API_RATE_LIMITING: '/api-rate-limiting',
    VERSIONING_DOCUMENTING_API_SWAGGER: '/versioning-documenting-api-swagger',
    UNIT_TESTING_XUNIT: '/unit-testing-xunit',
    MONITORING_APPLICATION_HEALTHCHECKS: '/monitoring-application-healthchecks',
    IMPROVING_PERFORMANCE_CACHING: '/improving-performance-caching',
    SCALING_OPTIMIZING_API: '/scaling-optimizing-api',
};